---
driver:
  name: azure
  subscription: "Free Trial"
  publish_settings_file: "/users/mattstratton/Downloads/freetrial.publishsettings"
  storage_account: "awesomechef"

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[azure-kitchen::default]
    attributes:
