---
driver:
  name: azure
  subscription: "Free Trial"
  publish_settings_file: "/users/mattstratton/Downloads/freetrial.publishsettings"
  storage_account: "awesomechef"

provisioner:
  name: chef_zero

platforms:
  - name: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_2-LTS-amd64-server-20121218-en-us-30GB

suites:
  - name: default
    run_list:
      - recipe[azure-kitchen::default]
    attributes:
